# Generated by Django 4.0.5 on 2022-06-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Email del usuario PK')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del usuario')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del usuario')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion del usuario')),
                ('password', models.CharField(max_length=100, verbose_name='Clave del usuario')),
                ('telefono', models.IntegerField(verbose_name='Telefono del usuario')),
            ],
        ),
    ]
